version: '3'

services:
#  app:
#    build: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/opt/app
#    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#    env_file:
#      - .env
#    depends_on:
#      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - app/config/resources/.env.local

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db


#  tests:
#    build: .
#    volumes:
#      - .:/opt/app
#    command: pytest -vv
#    env_file:
#      - .env.test


#  test-db:
#    image: postgres
#    ports:
#      - "15432:5432"
#    environment:
#      - POSTGRES_DB=usplit
#      - POSTGRES_USER=captain
#      - POSTGRES_PASSWORD=periscope