"""phone_number is removed

Revision ID: 610085bf4cae
Revises: 7a2956961f3f
Create Date: 2024-10-14 14:02:41.748275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610085bf4cae'
down_revision: Union[str, None] = '7a2956961f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###
